apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineHealthCheck
metadata:
  name: node-unhealthy-5m
spec:
  clusterName: tkc0804210946
  maxUnhealthy: 50%
  nodeStartupTimeout: 10m
  selector:
    matchLabels:
      machine-template-hash: "3675602100"
  unhealthyConditions:
  - type: Ready
    status: Unknown
    timeout: 300s
  - type: Ready
    status: "False"
    timeout: 300s

# https://cluster-api.sigs.k8s.io/tasks/healthcheck.html
