apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  storageClassName: tanzu-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
