apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc0804121305
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      count: 3
      class: best-effort-small
      storageClass: tanzu-storage
    workers:
      count: 2
      class: best-effort-small
      storageClass: tanzu-storage
  settings:
    storage:
      classes:
      - tanzu-storage
      defaultClass: tanzu-storage
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["10.51.0.0/16"]
      pods:
        cidrBlocks: ["10.50.0.0/16"]
      #proxy:
      #  httpProxy: http://proxy:port
      #  httpsProxy: http://proxy:port
      #  noProxy: 10.0.0.0/8,localhost,127.0.0.1
